=== Infogain-GenAI/my-agent-management-system/misc/resources/agent_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "capabilities": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "config": {
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        }
      },
      "required": [
        "key"
      ]
    },
    "created_at": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "provider_id": {
      "type": "string"
    },
    "persona_id": {
      "type": "string"
    },
    "user_id": {
      "type": "string"
    },
    "provider": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "features": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "agent_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "integration": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "config": {
          "type": "object",
          "properties": {
            "key": {
              "type": "string"
            }
          },
          "required": [
            "key"
          ]
        },
        "logo_link": {
          "type": "string"
        },
        "doc_link": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "type",
        "description",
        "status",
        "features",
        "agent_types",
        "integration",
        "config",
        "logo_link",
        "doc_link",
        "created_at",
        "updated_at"
      ]
    },
    "persona": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "updated_at": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "description",
        "created_at",
        "updated_at"
      ]
    },
    "users": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "user_id": {
            "type": "string"
          },
          "agent_id": {
            "type": "string"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "first_name": {
                "type": "string"
              },
              "last_name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "role": {
                "type": "string"
              },
              "created_at": {
                "type": "string"
              },
              "updated_at": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "first_name",
              "last_name",
              "email",
              "role",
              "created_at",
              "updated_at"
            ]
          }
        },
        "required": [
          "user_id",
          "agent_id",
          "user"
        ]
      }
    },
    "domains": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "domain_id": {
            "type": "string"
          },
          "agent_id": {
            "type": "string"
          },
          "domain": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              },
              "type": {
                "type": "string"
              },
              "created_at": {
                "type": "string"
              },
              "updated_at": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "type",
              "created_at",
              "updated_at"
            ]
          }
        },
        "required": [
          "domain_id",
          "agent_id",
          "domain"
        ]
      }
    },
    "metrics": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "agent_id": {
            "type": "string"
          },
          "provider_id": {},
          "domain_id": {},
          "persona_id": {},
          "user_id": {},
          "metric_type": {
            "type": "string"
          },
          "metric_value": {
            "type": "number"
          },
          "unit": {
            "type": "string"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "agent_id",
          "provider_id",
          "domain_id",
          "persona_id",
          "user_id",
          "metric_type",
          "metric_value",
          "unit",
          "created_at",
          "updated_at"
        ]
      }
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "status",
    "capabilities",
    "features",
    "config",
    "created_at",
    "updated_at",
    "provider_id",
    "persona_id",
    "user_id",
    "provider",
    "persona",
    "users",
    "domains",
    "metrics"
  ]
}

=== Infogain-GenAI/my-agent-management-system/misc/resources/agent.json
{
	"id": "cm805787h000hqyasawcn6v4t",
	"name": "Agent 1",
	"description": "Agent 1 Description",
	"status": "ACTIVE",
	"capabilities": [
		"CAPABILITY_1",
		"CAPABILITY_2"
	],
	"features": [
		"FEATURE_1",
		"FEATURE_2"
	],
	"config": {
		"key": "value"
	},
	"created_at": "2025-03-08T11:50:04.109Z",
	"updated_at": "2025-03-08T11:50:04.109Z",
	"provider_id": "cm805786n0002qyasdm98tz9w",
	"persona_id": "cm8057876000bqyaszcrn7yhm",
	"user_id": "cm805786f0000qyasuvnbqfo9",
	"provider": {
		"id": "cm805786n0002qyasdm98tz9w",
		"name": "AWS",
		"type": "PLATFORMS",
		"description": "Amazon Web Services",
		"status": "ONLINE",
		"features": [
			"FEATURE_1",
			"FEATURE_2"
		],
		"agent_types": [
			"PLANNER",
			"EXECUTOR"
		],
		"integration": [
			"API"
		],
		"config": {
			"key": "value"
		},
		"logo_link": "https://aws.amazon.com/logo.png",
		"doc_link": "https://aws.amazon.com/documentation",
		"created_at": "2025-03-08T11:50:04.079Z",
		"updated_at": "2025-03-08T11:50:04.079Z"
	},
	"persona": {
		"id": "cm8057876000bqyaszcrn7yhm",
		"name": "Developer",
		"description": "Software Developer",
		"created_at": "2025-03-08T11:50:04.099Z",
		"updated_at": "2025-03-08T11:50:04.099Z"
	},
	"users": [
		{
			"user_id": "cm805786f0000qyasuvnbqfo9",
			"agent_id": "cm805787h000hqyasawcn6v4t",
			"user": {
				"id": "cm805786f0000qyasuvnbqfo9",
				"first_name": "John",
				"last_name": "Doe",
				"email": "john.doe@example.com",
				"role": "PLATFORM_ADMIN",
				"created_at": "2025-03-08T11:50:04.072Z",
				"updated_at": "2025-03-08T11:50:04.072Z"
			}
		}
	],
	"domains": [
		{
			"domain_id": "cm805786w0006qyasoxym0rwd",
			"agent_id": "cm805787h000hqyasawcn6v4t",
			"domain": {
				"id": "cm805786w0006qyasoxym0rwd",
				"name": "Software Development",
				"type": "SOFTWARE_DEVELOPMENT",
				"created_at": "2025-03-08T11:50:04.089Z",
				"updated_at": "2025-03-08T11:50:04.089Z"
			}
		}
	],
	"metrics": [
		{
			"id": "cm8057884000qqyas40f5vtjw",
			"agent_id": "cm805787h000hqyasawcn6v4t",
			"provider_id": null,
			"domain_id": null,
			"persona_id": null,
			"user_id": null,
			"metric_type": "CPU",
			"metric_value": 75.5,
			"unit": "%",
			"created_at": "2025-03-08T11:50:04.132Z",
			"updated_at": "2025-03-08T11:50:04.132Z"
		},
		{
			"id": "cm8057884000vqyas8uovkobx",
			"agent_id": "cm805787h000hqyasawcn6v4t",
			"provider_id": null,
			"domain_id": null,
			"persona_id": null,
			"user_id": null,
			"metric_type": "Memory",
			"metric_value": 70.8,
			"unit": "%",
			"created_at": "2025-03-08T11:50:04.132Z",
			"updated_at": "2025-03-08T11:50:04.132Z"
		}
	]
}
